services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: backends
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/django/
    ports:
      - "8000:8000"
    env_file: 
      - ./.env

  celery:
    container_name: Django_Celery
    build:
      context: .
      dockerfile: Dockerfile.django
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/usr/src/django/
    env_file:
      - ./.env
