services:
  django:
    image: ${BACK_GCR_CONTAINER}
    container_name: backends
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/django/
    ports:
      - "8000:8000"
    env_file: 
      - ./.env
    networks:
      - mensclub-networks  

  celery:
    container_name: Django_Celery
    image: ${BACK_GCR_CONTAINER}
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/usr/src/django/
    env_file:
      - ./.env
    networks:
      - mensclub-networks  

networks:
  mensclub-networks:
    external: True