# Generated by Django 5.2 on 2025-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationTest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recommendation_code", models.IntegerField()),
                ("top_id", models.IntegerField()),
                ("bottom_id", models.IntegerField()),
                ("outer_id", models.IntegerField(blank=True, null=True)),
                ("shoes_id", models.IntegerField()),
                ("answer", models.TextField()),
                ("style", models.CharField(max_length=50)),
                ("total_price", models.IntegerField()),
                ("liked", models.BooleanField()),
                ("detail", models.TextField()),
                ("created_at", models.DateTimeField(blank=True)),
            ],
            options={
                "db_table": "recommendation_test",
                "managed": False,
            },
        ),
    ]
