# Generated by Django 5.2 on 2025-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Picked", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPicked",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "main_picked",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MainRecommend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("style", models.CharField(max_length=100)),
                ("total_price", models.IntegerField()),
                ("detail", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "main_recommend",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MensTableRefine",
            fields=[
                ("idx", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "mens_table_refine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Picked",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "picked",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recommendation_code", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("style", models.CharField(max_length=100)),
                ("total_price", models.IntegerField()),
                ("detail", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "recommend",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShoesRefine",
            fields=[
                ("idx", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "shoes_refine",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="RecommendationTest",
        ),
    ]
