services:
  nginx:
    container_name: proxy
    env_file:
      - ./.env
    environment:
      - PROXY_GCR_CONTAINER=${PROXY_GCR_CONTAINER}
    image: ${PROXY_GCR_CONTAINER}
    ports:
      - "80:80"
    networks:
      - mensclub-networks  

networks:
  mensclub-networks:
    external: True
  