FROM node:18-alpine

# 컨테이너 내 앱 디렉토리 생성
WORKDIR /usr/src/app

# package.json과 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 코드 복사
COPY . .

# 개발 서버 실행
CMD ["npm", "start"]