services:
  frontend:
    container_name: frontend
    env_file:
      - ./.env
    environment:
      - FRONT_GCR_CONTAINER=${FRONT_GCR_CONTAINER}
      - WATCHPACK_POLLING=true
    image: ${FRONT_GCR_CONTAINER}
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    networks:
      - mensclub-networks  

networks:
  mensclub-networks:
    external: true
