services:
  frontend:
    container_name: frontend
    env_file:
      - ./.env
    environment:
      - FRONT_GCR_CONTAINER=${FRONT_GCR_CONTAINER}
      - WATCHPACK_POLLING=true
    image: ${FRONT_GCR_CONTAINER}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # 로컬 파일 변경 시 컨테이너에 반영
      - /usr/src/app/node_modules # node_modules는 볼륨 매핑 제외
    networks:
      - mensclub-networks  

networks:
  mensclub-networks:
    external: true
