# Generated by Django 5.2 on 2025-05-09 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clothes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "recommendation_code",
                    models.CharField(
                        default="", editable=False, max_length=50, unique=True
                    ),
                ),
                ("answer", models.TextField(help_text="AI가 제공한 분석 응답")),
                (
                    "reasoning_generated",
                    models.BooleanField(default=False, help_text="추천 이유 생성 상태"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_price", models.IntegerField(blank=True, null=True)),
                (
                    "bottom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bottom",
                        to="clothes.clothes",
                    ),
                ),
                (
                    "outer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outer",
                        to="clothes.clothes",
                    ),
                ),
                (
                    "shoes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shoes",
                        to="clothes.shoes",
                    ),
                ),
                (
                    "top",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top",
                        to="clothes.clothes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommend_recommendation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationBookmark",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="recommend.recommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommend_bookmark",
                "ordering": ["-created_at"],
                "unique_together": {("user", "recommendation")},
            },
        ),
    ]
