# Generated by Django 5.2 on 2025-05-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommended",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("top_id", models.IntegerField()),
                ("bottom_id", models.IntegerField()),
                ("outer_id", models.IntegerField()),
                ("shoes_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommended",
            },
        ),
        migrations.CreateModel(
            name="Picked",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="clothes.recommended",
                    ),
                ),
            ],
            options={
                "db_table": "picked",
            },
        ),
    ]
