# Generated by Django 5.2 on 2025-05-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("season", models.CharField(blank=True, max_length=50, null=True)),
                ("goods_name", models.CharField(max_length=100)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("is_soldout", models.CharField(blank=True, max_length=50, null=True)),
                ("goods_url", models.URLField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "normal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "main_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "mens_table_refine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Shoes",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("season", models.CharField(blank=True, max_length=50, null=True)),
                ("goods_name", models.CharField(max_length=100)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("is_soldout", models.CharField(blank=True, max_length=50, null=True)),
                ("goods_url", models.URLField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "normal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "shoes_refine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_id", models.BigIntegerField(blank=True, null=True)),
                ("outer_id", models.BigIntegerField(blank=True, null=True)),
                ("bottom_id", models.BigIntegerField(blank=True, null=True)),
                ("shoes_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
