# Generated by Django 5.2 on 2025-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                ("idx", models.IntegerField(primary_key=True, serialize=False)),
                ("style", models.TextField(blank=True, null=True)),
                ("season", models.TextField(blank=True, null=True)),
                ("fit", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("goods_name", models.TextField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("is_soldout", models.BigIntegerField(blank=True, null=True)),
                ("goods_url", models.TextField(blank=True, null=True)),
                ("brand", models.TextField(blank=True, null=True)),
                ("normal_price", models.BigIntegerField(blank=True, null=True)),
                ("price", models.BigIntegerField(blank=True, null=True)),
                ("main_category", models.TextField(blank=True, null=True)),
                ("sub_category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.TextField(blank=True, null=True)),
                ("s3_path", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "clothes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Shoes",
            fields=[
                ("idx", models.IntegerField(primary_key=True, serialize=False)),
                ("color", models.TextField(null=True)),
                ("sub_category", models.TextField(null=True)),
                ("season", models.TextField(null=True)),
                ("goods_name", models.TextField(null=True)),
                ("thumbnail_url", models.TextField(null=True)),
                ("is_soldout", models.BigIntegerField(null=True)),
                ("goods_url", models.TextField(null=True)),
                ("brand", models.TextField(null=True)),
                ("normal_price", models.BigIntegerField(null=True)),
                ("price", models.BigIntegerField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("image_id", models.TextField(null=True)),
                ("s3_path", models.TextField(null=True)),
            ],
            options={
                "db_table": "shoes",
                "managed": False,
            },
        ),
    ]
