# Generated by Django 5.2 on 2025-05-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Picked",
        ),
        migrations.DeleteModel(
            name="Recommended",
        ),
    ]
