# Generated by Django 5.2 on 2025-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenTableTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top", models.CharField(max_length=255)),
                ("outwear", models.CharField(max_length=255)),
                ("bottom", models.CharField(max_length=255)),
                ("shoes", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "menstable_test",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ClothingItem",
        ),
    ]
