# Generated by Django 5.2 on 2025-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommended",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
