# Generated by Django 5.2 on 2025-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0002_recommended_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommended",
            name="user_id",
        ),
    ]
