# Generated by Django 5.2 on 2025-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0002_mentabletest_delete_clothingitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base64FileTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_data", models.TextField()),
            ],
            options={
                "db_table": "base64_file_test",
                "managed": False,
            },
        ),
    ]
