# Generated by Django 5.2 on 2025-04-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0003_base64filetest"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="base64filetest",
            table="save_image_test",
        ),
    ]
