# Generated by Django 5.2 on 2025-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0004_alter_base64filetest_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensTable",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("goods_name", models.CharField(max_length=255)),
                ("sub_category", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "menstable_test",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShoesTest",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("goods_name", models.CharField(max_length=255)),
                ("sub_category", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "shoes_test",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MenTableTest",
        ),
    ]
