name: Image Build & Push Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-cloud-connect:
    runs-on: ubuntu-latest 
  
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Configure Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Login to GCR
        run: |
          # GCP 서비스 계정 키를 임시 파일로 저장
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          
          # GCR에 로그인
          cat gcp-key.json | docker login -u _json_key --password-stdin https://asia-northeast3-docker.pkg.dev
          
          # 로그인 성공 확인
          echo "GCR 로그인 성공"
          
          # 보안을 위해 임시 파일 삭제
          rm gcp-key.json
      
      - name: Connect to server and check directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "서버 접속 성공"
            pwd
            ls -la
            echo "현재 디렉토리 확인 완료"